package main

// Code generated by "typedjson -interface Data *Foo *Bar"; DO NOT EDIT.

import (
	"encoding/json"
	"errors"
)

type DataTyped struct {
	Data
}

func (t DataTyped) MarshalJSON() ([]byte, error) {
	if t.Data == nil {
		return nil, errors.New("nil interface in DataTyped.Data")
	}
	typedString := t.Data.TypedJSON(nil)
	wrapper := struct {
		T string
		V Data
	}{
		T: typedString,
		V: t.Data,
	}
	return json.Marshal(&wrapper)
}

func (t *DataTyped) UnmarshalJSON(src []byte) error {
	var wrapper struct {
		T string
		V json.RawMessage
	}
	err := json.Unmarshal(src, &wrapper)
	if err != nil {
		return err
	}
	data, err := GetEmptyData(wrapper.T)
	if err != nil {
		return err
	}
	t.Data = data
	if err := json.Unmarshal(wrapper.V, t.Data); err != nil {
		return err
	}
	return nil
}

func GetEmptyData(typedString string) (Data, error) {
	switch typedString {
	case "*Foo":
		return &Foo{}, nil
	case "*Bar":
		return &Bar{}, nil

	default:
		return nil, errors.New("unknown type")
	}
}

func (s *Foo) TypedJSON(*DataTyped) string {
	return "*Foo"
}

func (s *Bar) TypedJSON(*DataTyped) string {
	return "*Bar"
}
